### ISSUE TITLE
AddScoped Http Client shows error cannot find http client 

### ISSUE THREAD

**Issue by liongkj** [jsakamoto/Toolbelt.Blazor.LoadingBar#15]
I was following microsoft [doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#blazor-webassembly) to register the DI for http client using http client so that I can automatically attach accesstoken to my request. However, this seems to make loading bar cannot find the http client.

```Error Message
blazor.webassembly.js:1 ﻿System.InvalidOperationException: Cannot resolve scoped service 'System.Net.Http.HttpClient' from root provider.
```

Any suggestions to solve this?

**Comment by jsakamoto** [comment]
Hi,
The problem that you encountered may be caused due to there are no considerations in this library about the scenario of registration HttpClinet to DI container as a scoped service.

Since Blazor WebAssembly v.3.2 preview 5, a Blazor Wasm project which is generated by dotnet project templates was register HttpClient as a transient or singleton service.

However, the latest project template (Blazor Wasm v.3.2.1) had been changed to generates the source code that registers HttpClient as a scoped service, like a document that you referenced.

I'll try to fix this problem.

The workaround at this time is, change the registration HttpClient as a transition or singleton service, not a scoped service.

![image](https://user-images.githubusercontent.com/95908/88182136-c90ea000-cc6a-11ea-97d1-aa2b0ff034f8.png)

**Comment by liongkj** [comment]
ya, i tried using AddTransient and the loading bar is working fine. However, I would like to keep the auto attach access token functionality of the add scoped, I will wait for your next update instead. Thanks!

**Comment by jsakamoto** [comment]
@liongkj 

I just published a fixed version v.12.0.1.

- https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/12.0.1

Please try it out!

P.S.
Thank you for your reporting! 👍

**Comment by liongkj** [comment]
Thanks, working as intended now
